# This is the main configuration file for your Supabase project.
# It's used by the Supabase CLI to manage your local development environment
# and to deploy your project to the Supabase platform.

[functions.sync-updated-bills]
# This is our main data pipeline, run daily by a cron job.
verify_jwt = false
import_map = "./functions/sync-updated-bills/deno.json"

[functions.verify-app-check]
# This function is called by the app for security and must not require a JWT.
verify_jwt = false
import_map = "./functions/verify-app-check/deno.json"

[functions.send-push-notifications]
# This function will be called with a service_role key and requires a valid JWT.
verify_jwt = true
import_map = "./functions/send-push-notifications/deno.json"

[functions.translate-bill]
verify_jwt = false
import_map = "./functions/translate-bill/deno.json"

[functions.translate-bills]
verify_jwt = false
import_map = "./functions/translate-bills/deno.json"

[functions.find-your-rep]
verify_jwt = false
import_map = "./functions/find-your-rep/deno.json"

[functions."summarize-simple"]
verify_jwt = false

[functions."summarize-simple-backfill"]
verify_jwt = false
