-- Create the table to store app configuration
CREATE TABLE app_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE app_config ENABLE ROW LEVEL SECURITY;

-- Policy: Allow authenticated users to read the configuration
CREATE POLICY "Allow authenticated users to read config"
ON app_config
FOR SELECT
TO authenticated
USING (true);

-- Insert the configuration values
-- Replace the placeholder values with your actual secrets
INSERT INTO app_config (key, value) VALUES
  ('EXPO_PUBLIC_OPENSTATES_API_KEY', 'YOUR_OPENSTATES_API_KEY'),
  ('EXPO_PUBLIC_LOCATIONIQ_API_KEY', 'YOUR_LOCATIONIQ_API_KEY'),
  ('EXPO_PUBLIC_RECAPTCHA_SITE_KEY', 'YOUR_RECAPTCHA_SITE_KEY'),
  ('EXPO_PUBLIC_FIREBASE_WEB_CONFIG', 'YOUR_FIREBASE_WEB_CONFIG');
