# This is the main configuration file for your Supabase project.
# It's used by the Supabase CLI to manage your local development environment
# and to deploy your project to the Supabase platform.

[functions.ingest-and-summarize]
# This function requires a service_role key, so we want to verify the user's JWT.
verify_jwt = true
import_map = "./functions/ingest-and-summarize/deno.json"

[functions.verify-app-check]
# This function must be called before a user is logged in, so we must disable JWT verification.
verify_jwt = false
import_map = "./functions/verify-app-check/deno.json"

[functions.bulk-import-dataset]
verify_jwt = false
import_map = "./functions/bulk-import-dataset/deno.json"