-- Persistent LegiScan API budget and cooldown guardrails.
-- This prevents cron/worker bugs from repeatedly spending public API queries.

CREATE TABLE IF NOT EXISTS public.legiscan_api_call_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint TEXT NOT NULL,
  resource_key TEXT NOT NULL DEFAULT 'global',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS legiscan_api_call_log_created_at_idx
  ON public.legiscan_api_call_log (created_at DESC);

CREATE INDEX IF NOT EXISTS legiscan_api_call_log_endpoint_resource_created_idx
  ON public.legiscan_api_call_log (endpoint, resource_key, created_at DESC);

ALTER TABLE public.legiscan_api_call_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS legiscan_api_call_log_service_role ON public.legiscan_api_call_log;
CREATE POLICY legiscan_api_call_log_service_role
  ON public.legiscan_api_call_log
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

REVOKE ALL ON public.legiscan_api_call_log FROM PUBLIC;
GRANT SELECT, INSERT, DELETE ON public.legiscan_api_call_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.legiscan_api_call_log_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.reserve_legiscan_api_call(
  p_endpoint TEXT,
  p_resource_key TEXT DEFAULT 'global',
  p_cooldown_seconds INTEGER DEFAULT 0,
  p_daily_limit INTEGER DEFAULT 900,
  p_monthly_limit INTEGER DEFAULT 25000
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_endpoint TEXT := NULLIF(BTRIM(p_endpoint), '');
  clean_resource_key TEXT := COALESCE(NULLIF(BTRIM(p_resource_key), ''), 'global');
  cooldown_seconds INTEGER := LEAST(GREATEST(COALESCE(p_cooldown_seconds, 0), 0), 31536000);
  daily_limit INTEGER := LEAST(GREATEST(COALESCE(p_daily_limit, 900), 1), 1000);
  monthly_limit INTEGER := LEAST(GREATEST(COALESCE(p_monthly_limit, 25000), 1), 30000);
  now_value TIMESTAMPTZ := now();
  last_called_at TIMESTAMPTZ;
  day_count INTEGER;
  month_count INTEGER;
  retry_after_seconds INTEGER;
BEGIN
  IF clean_endpoint IS NULL THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'missing_endpoint'
    );
  END IF;

  -- Serialize budget checks so concurrent Edge invocations cannot race past limits.
  PERFORM pg_advisory_xact_lock(2147483001);

  SELECT max(created_at)
    INTO last_called_at
  FROM public.legiscan_api_call_log
  WHERE endpoint = clean_endpoint
    AND resource_key = clean_resource_key;

  IF last_called_at IS NOT NULL
     AND last_called_at + make_interval(secs => cooldown_seconds) > now_value THEN
    retry_after_seconds := CEIL(
      EXTRACT(EPOCH FROM (last_called_at + make_interval(secs => cooldown_seconds) - now_value))
    )::INTEGER;

    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'cooldown',
      'endpoint', clean_endpoint,
      'resource_key', clean_resource_key,
      'last_called_at', last_called_at,
      'retry_after_seconds', retry_after_seconds
    );
  END IF;

  SELECT count(*)::INTEGER
    INTO day_count
  FROM public.legiscan_api_call_log
  WHERE created_at >= date_trunc('day', now_value);

  IF day_count >= daily_limit THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'daily_limit',
      'daily_count', day_count,
      'daily_limit', daily_limit
    );
  END IF;

  SELECT count(*)::INTEGER
    INTO month_count
  FROM public.legiscan_api_call_log
  WHERE created_at >= date_trunc('month', now_value);

  IF month_count >= monthly_limit THEN
    RETURN jsonb_build_object(
      'allowed', false,
      'reason', 'monthly_limit',
      'monthly_count', month_count,
      'monthly_limit', monthly_limit
    );
  END IF;

  INSERT INTO public.legiscan_api_call_log(endpoint, resource_key)
  VALUES (clean_endpoint, clean_resource_key);

  RETURN jsonb_build_object(
    'allowed', true,
    'endpoint', clean_endpoint,
    'resource_key', clean_resource_key,
    'daily_count', day_count + 1,
    'daily_limit', daily_limit,
    'monthly_count', month_count + 1,
    'monthly_limit', monthly_limit
  );
END;
$$;

REVOKE ALL ON FUNCTION public.reserve_legiscan_api_call(text, text, integer, integer, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reserve_legiscan_api_call(text, text, integer, integer, integer) TO service_role;

CREATE OR REPLACE VIEW public.v_legiscan_api_usage_30d AS
SELECT
  endpoint,
  resource_key,
  count(*) AS call_count,
  min(created_at) AS first_called_at,
  max(created_at) AS last_called_at
FROM public.legiscan_api_call_log
WHERE created_at >= now() - interval '30 days'
GROUP BY endpoint, resource_key;

GRANT SELECT ON public.v_legiscan_api_usage_30d TO service_role;

NOTIFY pgrst, 'reload schema';
